version: '3'
services:
  web:
    build: .
    restart: always
    ports:
      - "5000:5000"
    volumes:
      - "./data-volume:/app/cheers-webserver/code:rw"
    links:
      - redis
      - celery
  nginx:
    build: ./code/docker/prod/nginx
    ports:
      - "8000:8888"
    depends_on:
      - web
  celery:
    build: .
    command: celery -A courier_work.celery worker
    volumes:
      - '.:/app/cheers-webserver/celery'
    links:
      - redis
    depends_on:
      - redis
    container_name: cl01
  redis:
    image: redis:latest
    container_name: rd01