version: '3'
services:
  web:
    build: .
    restart: always
    ports:
      - "5000:5000"
    volumes:
      - "./data-volume:/app/cheers-webserver/code:rw"
    links:
      - redis
      - celery
  nginx:
    container_name: 'production-nginx-container'
    build: ./code/docker/prod/nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - type: volume
        source: ./dh-param/dhparam-2048.pem
        target: /etc/ssl/certs/dhparam-2048.pem
      - type: volume
        source: /docker-volumes/etc/letsencrypt/live/belit.mobi/fullchain.pem
        target: /etc/letsencrypt/live/belit.mobi/fullchain.pem
      - type: volume
        source: /docker-volumes/etc/letsencrypt/live/belit.mobi/privkey.pem
        target: /etc/letsencrypt/live/belit.mobi/privkey.pem
      - type: volume
        source: /docker-volumes/data/letsencrypt
        target: /data/letsencrypt
      - type: bind
        source: /images
        target: /static/images
    depends_on:
      - web
  celery:
    build: .
    command: celery -A courier_work.celery worker
    volumes:
      - '.:/app/cheers-webserver/celery'
    links:
      - redis
    depends_on:
      - redis
    container_name: cl01
  redis:
    image: redis:latest
    container_name: rd01